name: app
description: '보틀노트 공식 앱'
publish_to: 'none'

version: 1.0.6+32

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.6
  logger: ^2.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  kakao_flutter_sdk: ^1.9.7+3
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.3.1
  connectivity_plus: ^6.0.5
  envied: ^1.1.1
  flutter_svg: ^2.0.10+1
  svg_path_parser: ^1.1.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: '^0.13.1'
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: 'AppIcon'
  image_path_ios: 'assets/logo/icon-square.png'
  image_path_android: 'assets/logo/icon-square.png'
  remove_alpha_ios: true

flutter_native_splash:
  color: '#e58257' # 배경색
  image: 'assets/logo/bottle_note_logo_white.svg'
  android: true
  ios: false # 이미 iOS는 수동으로 했으니 false
  android_12:
    color: '#e58257'
    image: 'assets/logo/bottle_note_logo_white.svg'
